"""Alterar densidade_real para cor

Revision ID: 1ced13cedfc1
Revises: 947e67813c79
Create Date: 2025-11-30 18:06:46.796320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ced13cedfc1'
down_revision = '947e67813c79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cor', sa.String(length=30), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producao', schema=None) as batch_op:
        batch_op.drop_column('cor')

    # ### end Alembic commands ###
