"""Alterar cor , retirada a coluan

Revision ID: 947e67813c79
Revises: 7a5f3e6d36b8
Create Date: 2025-11-30 18:04:33.754831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '947e67813c79'
down_revision = '7a5f3e6d36b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producao', schema=None) as batch_op:
        batch_op.drop_column('densidade_real')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('densidade_real', sa.FLOAT(), nullable=False))

    # ### end Alembic commands ###
