"""adicionando campo observacao em movimentacao

Revision ID: 99ac928b9fce
Revises: ad3f836fcdf8
Create Date: 2026-02-22 00:53:02.548544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99ac928b9fce'
down_revision = 'ad3f836fcdf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimentacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacao', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimentacao', schema=None) as batch_op:
        batch_op.drop_column('observacao')

    # ### end Alembic commands ###
